---
# Kargo Project - Each team manages their own Kargo manifests
# This file lives in: github.com/csz-akuity/kargo-demo-gitops (main branch)
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-demo-gitops
  namespace: kargo-demo-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  promotionPolicies:
    - stage: test
      autoPromotionEnabled: true
    - stage: uat
      autoPromotionEnabled: true
    - stage: prod
      autoPromotionEnabled: false
