---
# Base Kargo Project - Generic template
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-demo-gitops
  namespace: kargo-demo-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-1"