---
# Test stage - Team Beta specific
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo-gitops-team-beta
  labels:
    team: beta
spec:
  # Request Freight directly from the warehouse
  requestedFreight:
    - origin:
        kind: Warehouse
        name: kargo-demo-gitops-team-beta
      sources:
        direct: true
  
  # Promotion template - how to promote Freight to this stage
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/csz-akuity/kargo-demo-gitops.git
            checkout:
              - branch: team-beta-dev
                path: ./src
        - uses: kustomize-set-image
          as: update-image
          config:
            path: ./src/base
            images:
              - image: public.ecr.aws/nginx/nginx
                tag: ${{ imageFrom('public.ecr.aws/nginx/nginx').Tag }}
        - uses: kustomize-build
          config:
            path: ./src/stages/test
            outPath: ./src/build
        - uses: git-commit
          config:
            path: ./src
            message: "Update nginx image for test stage - Team Beta"
        - uses: git-push
          config:
            path: ./src

---
# UAT stage - Team Beta specific
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: kargo-demo-gitops-team-beta
  labels:
    team: beta
spec:
  # Request Freight from test stage
  requestedFreight:
    - origin:
        kind: Warehouse
        name: kargo-demo-gitops-team-beta
      sources:
        stages:
          - test
  
  # Promotion template
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/csz-akuity/kargo-demo-gitops.git
            checkout:
              - branch: team-beta-dev
                path: ./src
        - uses: kustomize-set-image
          as: update-image
          config:
            path: ./src/base
            images:
              - image: public.ecr.aws/nginx/nginx
                tag: ${{ imageFrom('public.ecr.aws/nginx/nginx').Tag }}
        - uses: kustomize-build
          config:
            path: ./src/stages/uat
            outPath: ./src/build
        - uses: git-commit
          config:
            path: ./src
            message: "Update nginx image for uat stage - Team Beta"
        - uses: git-push
          config:
            path: ./src
  
  # Simple verification
  verification:
    analysisTemplates:
      - name: verify-deployment-health-team-beta

---
# Production stage - Team Beta specific
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-demo-gitops-team-beta
  labels:
    team: beta
spec:
  # Request Freight from uat stage
  requestedFreight:
    - origin:
        kind: Warehouse
        name: kargo-demo-gitops-team-beta
      sources:
        stages:
          - uat
  
  # Promotion template
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/csz-akuity/kargo-demo-gitops.git
            checkout:
              - branch: team-beta-dev
                path: ./src
        - uses: kustomize-set-image
          as: update-image
          config:
            path: ./src/base
            images:
              - image: public.ecr.aws/nginx/nginx
                tag: ${{ imageFrom('public.ecr.aws/nginx/nginx').Tag }}
        - uses: kustomize-build
          config:
            path: ./src/stages/prod
            outPath: ./src/build
        - uses: git-commit
          config:
            path: ./src
            message: "Update nginx image for prod stage - Team Beta"
        - uses: git-push
          config:
            path: ./src
  
  # Verification before considering promotion successful
  verification:
    analysisTemplates:
      - name: verify-deployment-health-team-beta
