---
# Simple verification job - Team Beta specific
# No GCP dependencies, just uses built-in kubectl
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: verify-deployment-health-team-beta
  namespace: kargo-demo-gitops-team-beta
  labels:
    team: beta
spec:
  metrics:
    - name: check-deployment-ready
      initialDelay: 10s
      successCondition: result == "true"
      provider:
        job:
          spec:
            template:
              spec:
                serviceAccountName: default
                restartPolicy: Never
                containers:
                  - name: verify
                    image: bitnami/kubectl:latest
                    command:
                      - /bin/sh
                      - -c
                      - |
                        # Simple check - just return success for testing
                        # In a real scenario, this would check actual deployment health
                        echo "Verification job running for Team Beta..."
                        echo "Checking deployment health..."
                        sleep 5
                        echo "true"
