apiVersion: v1
kind: ConfigMap
metadata:
  name: kargo-demo-html
  labels:
    team: alpha
    environment: development
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Team Alpha - Kargo Demo</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                color: white;
                margin: 0;
                padding: 20px;
                min-height: 100vh;
            }
            .container {
                max-width: 800px;
                margin: 0 auto;
                text-align: center;
                padding: 40px 20px;
            }
            h1 {
                font-size: 3em;
                margin-bottom: 20px;
                text-shadow: 2px 2px 4px rgba(0,0,0,0.3);
            }
            .team-badge {
                background: rgba(255,255,255,0.2);
                padding: 10px 20px;
                border-radius: 25px;
                display: inline-block;
                margin: 20px 0;
                font-weight: bold;
            }
            .features {
                display: grid;
                grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
                gap: 20px;
                margin-top: 40px;
            }
            .feature {
                background: rgba(255,255,255,0.1);
                padding: 20px;
                border-radius: 10px;
                backdrop-filter: blur(10px);
            }
            .status {
                margin-top: 40px;
                padding: 20px;
                background: rgba(0,255,0,0.2);
                border-radius: 10px;
                border: 2px solid rgba(0,255,0,0.5);
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🚀 Kargo Demo</h1>
            <div class="team-badge">Team Alpha - Blue Theme</div>
            
            <p>Welcome to Team Alpha's Kargo demonstration environment!</p>
            
            <div class="features">
                <div class="feature">
                    <h3>📊 Analytics</h3>
                    <p>Advanced analytics enabled</p>
                </div>
                <div class="feature">
                    <h3>🎨 Blue Theme</h3>
                    <p>Custom blue color scheme</p>
                </div>
                <div class="feature">
                    <h3>⚡ Performance</h3>
                    <p>Optimized for development</p>
                </div>
                <div class="feature">
                    <h3>🔧 Features</h3>
                    <p>2 replicas running</p>
                </div>
            </div>
            
            <div class="status">
                <h3>✅ Deployment Status</h3>
                <p>Team Alpha environment is running successfully!</p>
                <p><strong>Environment:</strong> Development</p>
                <p><strong>Team:</strong> Alpha</p>
                <p><strong>Theme:</strong> Blue</p>
            </div>
        </div>
    </body>
    </html>
