apiVersion: v1
kind: ConfigMap
metadata:
  name: kargo-demo-html
  labels:
    team: beta
    environment: development
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Team Beta - Kargo Demo</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                background: linear-gradient(135deg, #11998e 0%, #38ef7d 100%);
                color: white;
                margin: 0;
                padding: 20px;
                min-height: 100vh;
            }
            .container {
                max-width: 800px;
                margin: 0 auto;
                text-align: center;
                padding: 40px 20px;
            }
            h1 {
                font-size: 3em;
                margin-bottom: 20px;
                text-shadow: 2px 2px 4px rgba(0,0,0,0.3);
            }
            .team-badge {
                background: rgba(255,255,255,0.2);
                padding: 10px 20px;
                border-radius: 25px;
                display: inline-block;
                margin: 20px 0;
                font-weight: bold;
            }
            .features {
                display: grid;
                grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
                gap: 20px;
                margin-top: 40px;
            }
            .feature {
                background: rgba(255,255,255,0.1);
                padding: 20px;
                border-radius: 10px;
                backdrop-filter: blur(10px);
            }
            .status {
                margin-top: 40px;
                padding: 20px;
                background: rgba(0,255,0,0.2);
                border-radius: 10px;
                border: 2px solid rgba(0,255,0,0.5);
            }
            .performance-indicator {
                background: rgba(255,255,0,0.2);
                padding: 10px;
                border-radius: 5px;
                margin: 10px 0;
                border: 1px solid rgba(255,255,0,0.5);
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>⚡ Kargo Demo</h1>
            <div class="team-badge">Team Beta - Green Theme</div>
            
            <p>Welcome to Team Beta's High-Performance Kargo demonstration environment!</p>
            
            <div class="performance-indicator">
                <strong>🚀 Performance Mode Active</strong>
            </div>
            
            <div class="features">
                <div class="feature">
                    <h3>⚡ Performance</h3>
                    <p>High-performance mode enabled</p>
                </div>
                <div class="feature">
                    <h3>📊 Monitoring</h3>
                    <p>Advanced monitoring active</p>
                </div>
                <div class="feature">
                    <h3>🎨 Green Theme</h3>
                    <p>Custom green color scheme</p>
                </div>
                <div class="feature">
                    <h3>🔧 Features</h3>
                    <p>3 replicas running</p>
                </div>
            </div>
            
            <div class="status">
                <h3>✅ Deployment Status</h3>
                <p>Team Beta environment is running at peak performance!</p>
                <p><strong>Environment:</strong> Development</p>
                <p><strong>Team:</strong> Beta</p>
                <p><strong>Theme:</strong> Green</p>
                <p><strong>Performance:</strong> High</p>
            </div>
        </div>
    </body>
    </html>